### PR TITLE
Pause on Click and Resize Height on window.resize

### PR DESCRIPTION
**Pull request by jsumnersmith**
Added methods for (1)pausing on click events and (2)resizing slidesho…w height on window resize.

### CODE REVIEW

**Comment by jsumnersmith** [comment]
Notably, these are both configurable options for the plugin (though, arguable, the resize event shoudl default to `true`).

**Comment by boutell** [comment]
Interesting. I think the existing behavior on click was to reset the timer,
but not fully pause. Your option is to fully pause and not auto-advance
anymore?

On Thu, Nov 19, 2015 at 10:19 AM, Joel Smith notifications@github.com
wrote:

> Notably, these are both configurable options for the plugin (though,
> arguable, the resize event shoudl default to true).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/punkave/jquery-projector/pull/1#issuecomment-158087113
> .

## 

*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by jsumnersmith** [comment]
@boutell All set to merge, now.

**Comment by jsumnersmith** [comment]
Yeah, @boutell. To your point above about the pause vs. reset, we had a legitimate request for it. I think there's also room in the future for connecting that little function to a pause/play button.

**Comment by boutell** [comment]
Oh sure. I was just clarifying that it did something new, which it does.

On Thu, Nov 19, 2015 at 1:27 PM, Joel Smith notifications@github.com
wrote:

> Yeah, @boutell https://github.com/boutell. To your point above about
> the pause vs. reset, we had a legitimate request for it. I think there's
> also room in the future for connecting that little function to a pause/play
> button.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/punkave/jquery-projector/pull/1#issuecomment-158147149
> .

## 

*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Pull request merged**
